### ISSUE TITLE
Role fails to install JRE on Ubuntu 14.04

### ISSUE THREAD

**Issue by danielkza** [kevincoakley/ansible-role-zeppelin#4]
It manually skips the package installation step:

``` yaml
- name: Download and install the required packages (apt)
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ zeppelin_packages }}"
  when: ansible_os_family == "Debian" and ansible_distribution_version != '14.04'
```

Which is problematic, since it means the role will complete without actually succeeding. It should actually verify that Java is installed through some other means (such as having a custom java home set), or attempt to do the install in 14.04 anyway - it will succeed if a custom repository is installed, and fail otherwise.
