### ISSUE TITLE
Role working dir isn't used, making download to permanent storage impossible, making the role take a long time to run

### ISSUE THREAD

**Issue by danielkza** [kevincoakley/ansible-role-zeppelin#7]
It seems Zeppelin is always downloaded to /tmp, hence being re-downloaded in systems in which /tmp is ephemeral. The `zeppelin_working_directory` variable exists, but seems to be unused.

**Comment by kevincoakley** [comment]
Let me take a look at this tomorrow.

The task shouldn't be downloading to /tmp if /opt/zeppelin-{{ zeppelin_version }}-bin-all exists:

```yaml
- name: Check if the version of Zeppelin already exists
  stat:
    path: "/opt/zeppelin-{{ zeppelin_version }}-bin-all"
  register: zeppelin_install_path

- name: Download Zeppelin
  get_url:
    url: "{{ zeppelin_download_url }}"
    dest: "/tmp/zeppelin-{{ zeppelin_version }}.tgz"
  when: zeppelin_install_path.stat.exists == False
```

I will test that this is working properly tomorrow.

`zeppelin_working_directory` is used in `/templates/zeppelin.service.j2`
